// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Cryptography")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Cryptography")]
[assembly: AssemblyProductAttribute("Cryptography")]
[assembly: GuidAttribute("9ca72a18-42db-4181-b011-36226861af35")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
