// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Configuration")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Configuration")]
[assembly: AssemblyProductAttribute("Configuration")]
[assembly: GuidAttribute("28c6b3ed-c9b5-417c-8e99-c24b450de618")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
