version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2013
environment:
  matrix:
  - {}
build_script:
- cmd: build.bat
test: off
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: appveyor
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true