// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.ContainerManager.SimpleInjector.WebApi")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.ContainerManager.SimpleInjector.WebApi")]
[assembly: AssemblyProductAttribute("ContainerManager SimpleInjector WebApi")]
[assembly: GuidAttribute("41a971f9-06d1-4e50-ab3a-7fedb7fc4710")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
