// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Shared")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Shared")]
[assembly: AssemblyProductAttribute("Shared")]
[assembly: GuidAttribute("7323e348-0ae0-4f75-a2d8-adff0f03c04b")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
