// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Web")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Web")]
[assembly: AssemblyProductAttribute("Web")]
[assembly: GuidAttribute("92fd7376-973c-4e0d-8739-1a42ab860018")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
