// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Logging")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Logging")]
[assembly: AssemblyProductAttribute("Logging")]
[assembly: GuidAttribute("6089782a-ea12-4f14-9d24-bcab9f9f0163")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
