// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Authentication")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Authentication")]
[assembly: AssemblyProductAttribute("Authentication")]
[assembly: GuidAttribute("9493dae8-2559-4a54-8ff2-8759b5cfa760")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
