// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.ImageTransformation")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.ImageTransformation")]
[assembly: AssemblyProductAttribute("Transformation")]
[assembly: GuidAttribute("370ff938-8cdb-4a93-8e48-c85d52808e03")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
