// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Web.MVC")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Web.MVC")]
[assembly: AssemblyProductAttribute("Web MVC")]
[assembly: GuidAttribute("7398f722-b0e4-405e-881d-7277074abc18")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
