// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Expressions")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Expressions")]
[assembly: AssemblyProductAttribute("Expressions")]
[assembly: GuidAttribute("10ba2aa7-0828-4dd2-8c22-a123255e207c")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
