/* ---------- SE OS OBJETOS JÁ EXISTIREM - DROP ---------- */
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Ocupation;
DROP TABLE IF EXISTS ArtistGenre;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS WT_NOTICIA;

/* ---------- TABELAS TRANSACIONAIS ---------- */
CREATE TABLE Person
(
	IdPerson		INTEGER         		NOT NULL PRIMARY KEY AUTOINCREMENT
,	IdOcupation		INTEGER         		NOT NULL
,	PersonName		VARCHAR(200)    		NOT NULL
,	Gender			VARCHAR(50)         		NULL
,	Created			DATETIME				NOT NULL DEFAULT (DATETIME('NOW', 'LOCALTIME'))
,	Updated			DATETIME           			NULL
,	Activated		BIT						NOT NULL DEFAULT 1
,   FOREIGN KEY (IdOcupation) REFERENCES Ocupation(IdOcupation)
);

CREATE TABLE Ocupation
(
	IdOcupation		INTEGER					NOT NULL PRIMARY KEY AUTOINCREMENT
,	OcupationName	VARCHAR(200)			NOT NULL
,	Created			DATETIME				NOT NULL DEFAULT (DATETIME('NOW', 'LOCALTIME'))
,	Updated			DATETIME					NULL
,	Activated		BIT						NOT NULL DEFAULT 1
);

CREATE TABLE Artist
(
	IdArtist		INTEGER					NOT NULL PRIMARY KEY AUTOINCREMENT
,	Name			VARCHAR(200)    		NOT NULL
);

CREATE TABLE Genre
(
	IdGenre			INTEGER					NOT NULL PRIMARY KEY AUTOINCREMENT
,	Name			VARCHAR(200)    		NOT NULL
);

CREATE TABLE ArtistGenre
(
	IdArtistGenre	INTEGER					NOT NULL PRIMARY KEY AUTOINCREMENT
,	IdArtist		INTEGER					NOT NULL
,	IdGenre			INTEGER					NOT NULL
,   FOREIGN KEY (IdArtist) REFERENCES Artist (IdArtist)
,   FOREIGN KEY (IdGenre)  REFERENCES Genre  (IdGenre)
);

/* Tabela para teste de CRUD */
CREATE TABLE WT_NOTICIA
(
	ID_NOTICIA 			INTEGER				NOT NULL PRIMARY KEY AUTOINCREMENT
,	DSC_TITULO 			VARCHAR(150) 	  	NOT NULL
,	DSC_DESCRICAO 		TEXT 				NOT NULL
,	DSC_AUTOR			VARCHAR(100) 		    NULL
,	DAT_NOTICIA 		DATETIME			NOT NULL
,	DAT_CADASTRO 		DATETIME 		    NOT NULL
,	DAT_ALTERACAO 		DATETIME 			    NULL
);

