// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.ContainerManager.DryIoc.Mvc")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.ContainerManager.DryIoc.Mvc")]
[assembly: AssemblyProductAttribute("ContainerManager DryIoc Mvc")]
[assembly: GuidAttribute("1e10e9fa-c756-465f-b106-a985940da8cb")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
