// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Repository")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Repository")]
[assembly: AssemblyProductAttribute("Repository")]
[assembly: GuidAttribute("a2718b96-3f93-4d29-8942-e841f9eb5457")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
