// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Core")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Core")]
[assembly: AssemblyProductAttribute("Core")]
[assembly: GuidAttribute("ad0698e7-cd21-4340-8e6d-b4c6624e8fa8")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
