// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Extensions")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Extensions")]
[assembly: AssemblyProductAttribute("Extensions")]
[assembly: GuidAttribute("68100b12-1020-42ca-bea6-3e0cd9ddd040")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
