// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Abstraction")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Abstraction")]
[assembly: AssemblyProductAttribute("Abstraction")]
[assembly: GuidAttribute("5b3d5261-8415-433c-a27d-b22ca4e991b7")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
