// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Validation")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Validation")]
[assembly: AssemblyProductAttribute("Validation")]
[assembly: GuidAttribute("7a23f19f-96ee-44c7-81d9-3cdd4cb7b9f8")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
