// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Data")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Data")]
[assembly: AssemblyProductAttribute("Data")]
[assembly: GuidAttribute("4e0a9c6c-3368-4b83-92f5-6fda2679c434")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
