// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.ContainerManager")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.ContainerManager")]
[assembly: AssemblyProductAttribute("ContainerManager")]
[assembly: GuidAttribute("82a88e93-4c95-4db7-ad7d-8f1f367c4034")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
