// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.FTP")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.FTP")]
[assembly: AssemblyProductAttribute("FTP")]
[assembly: GuidAttribute("6671d840-ca72-4f9a-9624-7e3ffa97f520")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
