// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.Repository.EF6")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.Repository.EF6")]
[assembly: AssemblyProductAttribute("Repository Entity Framework 6")]
[assembly: GuidAttribute("5ce716f2-e7c2-4149-abf8-4ad319bf96d8")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
