// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("IOC.FW.POP3")]
[assembly: AssemblyDescriptionAttribute("IOC.FW.POP3")]
[assembly: AssemblyProductAttribute("POP3")]
[assembly: GuidAttribute("8cf26fb8-dfc9-485f-a997-fddaa5282aae")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.0.0";
        internal const string InformationalVersion = "3.0.0";
    }
}
